apiVersion: v1
kind: PervistentVolumeClaim
metadata: 
    name: pvc-azuriom-data
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi

---

apiVersion: v1
kind: PervistentVolumeClaim
metadata: 
    name: pvc-azuriom-vhost
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 512Mi

---

apiVersion: v1
kind: PervistentVolumeClaim
metadata: 
    name: pvc-azuriom-ssl
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 512Mi